In [118]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix # اضافه کردن confusion_matrix
import sklearn.preprocessing as preprocessing
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

In [102]:
file_path = 'D:/lab/home_care_dataset33.csv'

In [103]:
 df = pd.read_csv(file_path)

In [104]:
df

,سن,تشخیص نهایی,وضعیت ترخیص,سطح مراقبتی هنگام ترخیص,بیماری زمینه ای,نام بیماری زمینه ای,اتصالات بیمار در روز ترخیص,تهویه بیمار در زمان ترخیص,وضعیت زخم بیمار در روز ترخیص,محل زخم,درجه زخم,خدمات پرستاری مورد نیاز,نیاز به ویزیت پزشک در منزل,وسایل کمک حرکتی مورد نیاز,مرکز_مراقبت_مقصد
0,69,4,4,1,2,8,1,1,3,5,2,2,2,3,1
1,32,10,2,3,2,5,1,2,1,3,5,3,1,4,1
2,89,8,2,1,2,7,0,2,3,2,3,1,1,1,1
3,78,8,1,2,1,4,2,2,3,4,4,5 و 2,1,1,1
4,38,3,3,1,1,2,5,1,2,6,4,4 و 2,2,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,42,10,3,2,1,4,5,1,2,2,1,1 و 3,1,1,1
996,92,7,2,2,2,6,0,2,2,5,5,4 و 3,1,5,3
997,55,6,2,3,1,4,2,1,2,6,1,5,2,1,1
998,19,1,3,1,2,1,1,1,2,5,3,3,1,1,2
999,24,2,3,2,2,6,6,1,4,2,2,4,2,1,1

In [105]:
del df['خدمات پرستاری مورد نیاز']

In [106]:
target_column = 'مرکز_مراقبت_مقصد'

In [107]:
X = df.drop(columns=[target_column])

In [110]:
X.head()

,سن,تشخیص نهایی,وضعیت ترخیص,سطح مراقبتی هنگام ترخیص,بیماری زمینه ای,نام بیماری زمینه ای,اتصالات بیمار در روز ترخیص,تهویه بیمار در زمان ترخیص,وضعیت زخم بیمار در روز ترخیص,محل زخم,درجه زخم,نیاز به ویزیت پزشک در منزل,وسایل کمک حرکتی مورد نیاز
0,69,4,4,1,2,8,1,1,3,5,2,2,3
1,32,10,2,3,2,5,1,2,1,3,5,1,4
2,89,8,2,1,2,7,0,2,3,2,3,1,1
3,78,8,1,2,1,4,2,2,3,4,4,1,1
4,38,3,3,1,1,2,5,1,2,6,4,2,3

In [111]:
Y = df[target_column]

In [254]:
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: مرکز_مراقبت_مقصد, dtype: int64

In [255]:
from sklearn.linear_model import LogisticRegression

In [256]:
from sklearn.linear_model import LogisticRegression

In [257]:
clf_lr=LogisticRegression()
clf_lr.fit(X,Y)

C:\Users\darman-it\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [258]:
from sklearn.model_selection import train_test_split

In [259]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [260]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(800, 13) (200, 13) (800,) (200,)

In [261]:
clf_LR=LogisticRegression()
clf_LR.fit(X_train,Y_train)

C:\Users\darman-it\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [262]:
Y_test_pred=clf_LR.predict(X_test)

In [263]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [264]:
confusion_matrix(Y_test,Y_test_pred)

array([[122,   0,   0],
       [ 57,   0,   0],
       [ 21,   0,   0]])

In [265]:
accuracy_score(Y_test,Y_test_pred)

0.61

In [266]:
from sklearn import preprocessing
scaler=preprocessing.StandardScaler().fit(X_train)
X_train_s=scaler.transform(X_train)

In [267]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn_1=KNeighborsClassifier(n_neighbors=1)
clf_knn_1.fit(X_train_s,Y_train)

KNeighborsClassifier(n_neighbors=1)

In [268]:
confusion_matrix(Y_test,clf_knn_1.predict(X_test_s))

array([[80, 31, 11],
       [35, 19,  3],
       [10,  8,  3]])

In [269]:
scaler=preprocessing.StandardScaler().fit(X_test)
X_test_s=scaler.transform(X_test)

In [270]:
X_test_s

array([[-0.13746167,  0.34633805, -1.294014  , ..., -0.01046427,
        -0.91370804, -0.00340603],
       [ 1.71038372, -0.39055142, -1.294014  , ...,  0.68715402,
        -0.91370804, -1.36581934],
       [ 0.89913452,  1.82011698,  0.49700884, ..., -1.40570087,
        -0.91370804, -0.68461269],
       ...,
       [ 0.17802413, -1.49588561, -1.294014  , ..., -1.40570087,
         1.0944415 ,  1.35900728],
       [ 0.53857933,  0.34633805,  0.49700884, ...,  1.38477232,
         1.0944415 , -0.68461269],
       [ 1.43996732, -1.49588561,  1.39252025, ...,  0.68715402,
        -0.91370804, -0.00340603]], shape=(200, 13))

In [271]:
accuracy_score(Y_test,clf_knn_1.predict(X_test_s))

0.51

In [272]:
clf_knn_1=KNeighborsClassifier(n_neighbors=3)
clf_knn_1.fit(X_train_s,Y_train)
accuracy_score(Y_test,clf_knn_1.predict(X_test_s))

0.525

In [273]:
from sklearn.model_selection import GridSearchCV

In [282]:
params={'n_neighbors':(1,50)}

In [283]:
grid_search_cv=GridSearchCV(KNeighborsClassifier(),params)

In [276]:
grid_search_cv.fit(X_train_s,Y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': (1, 31)})

In [277]:
grid_search_cv.best_params_

{'n_neighbors': 31}

In [278]:
optimised_KNN=grid_search_cv.best_estimator_

In [279]:
Y_test_pred=optimised_KNN.predict(X_test_s)

In [280]:
confusion_matrix(Y_test,Y_test_pred)

array([[119,   3,   0],
       [ 57,   0,   0],
       [ 21,   0,   0]])

In [281]:
accuracy_score(Y_test,Y_test_pred)

0.595